import { coreBlocks } from './blocks/core.js';
import type { CinematicBlueprint, MotionBlock, StyleAffinity } from './types.js';

function recipe(
    id: string,
    name: string,
    description: string,
    category: MotionBlock['category'],
    beatRole: MotionBlock['beatRole'],
    tags: string[],
    promptSnippet: string,
    styleAffinity: StyleAffinity[] = ['any']
): MotionBlock {
    return {
        id,
        name,
        description,
        category,
        tags,
        styleAffinity,
        beatRole,
        runtime: false,
        promptSnippet,
    };
}

/** Recipe / blueprint-style motion blocks (LLM composes with GSAP + optional core __block). */
const recipeBlocks: MotionBlock[] = [
    recipe('terminal-typing', 'Terminal Typing', 'Con trỏ gõ lệnh terminal tối màu.', 'code', 'insight',
        ['terminal', 'code'],
        'Prefer __block("code-diff") with kind:code lines; animate typewriter feel on .vb-code-text.',
        ['modern', 'minimal']),
    recipe('dataviz-countup', 'Metric Count-up', 'Số lớn đếm lên + micro label.', 'dataviz', 'proof',
        ['stat', 'number'],
        'Use __block("bar-chart") for multi metrics OR a single .stat-num with gsap proxy count-up.',
        ['modern', 'classic', 'minimal']),
    recipe('bar-chart-race', 'Bar Chart Race', 'Các cột đua độ dài theo beat.', 'dataviz', 'proof',
        ['race', 'chart'],
        'Use __block("bar-chart") + staggered __block.animate with short offsets.',
        ['modern']),
    recipe('device-surface-showcase', 'Device Surface Alias', 'Alias device showcase.', 'device', 'insight',
        ['device'],
        'Call __block("device-showcase", ...).'),
    recipe('kinetic-type-beats', 'Kinetic Type Alias', 'Alias kinetic type.', 'kinetic-type', 'hook',
        ['type'],
        'Call __block("kinetic-type", ...).'),
    recipe('lower-third-clean', 'Lower Third Clean', 'Thanh tên + role góc dưới.', 'lower-third', 'any',
        ['lt', 'name'],
        'Build a slim bar + kicker + name; slide in from left with power3.out; keep ≤2 lines.',
        ['classic', 'modern']),
    recipe('lower-third-neon', 'Lower Third Neon', 'Lower-third viền neon.', 'lower-third', 'any',
        ['lt', 'neon'],
        'Hairline neon border, accent glow, slide+fade; no glass card clutter.',
        ['modern']),
    recipe('lower-third-editorial', 'Lower Third Editorial', 'Serif nameplate tạp chí.', 'lower-third', 'any',
        ['lt', 'editorial'],
        'Serif name + hairline rule; slow power2.out glide; classic palette.',
        ['classic']),
    recipe('logo-outro', 'Logo Outro', 'Logo scale + brand lockup kết thúc.', 'cinematic', 'cta',
        ['logo', 'outro'],
        'Centered brand mark + short tagline; scale from 0.9→1, opacity; end freeze 0.4s before scene exit.',
        ['modern', 'classic', 'minimal']),
    recipe('glitch-title', 'Glitch Title', 'Tiêu đề lệch RGB / slice.', 'kinetic-type', 'hook',
        ['glitch', 'hook'],
        'Duplicate title layers with clip-path offsets in cyan/magenta; finite shake (repeat:1-2), never infinite.',
        ['modern']),
    recipe('mask-reveal-title', 'Mask Reveal Title', 'Chữ lộ qua mask clip.', 'kinetic-type', 'hook',
        ['mask', 'reveal'],
        'Animate clip-path inset or overflow hidden wipe left→right on title.',
        ['minimal', 'modern']),
    recipe('split-flap-board', 'Split-flap Board', 'Bảng lật chữ sân bay.', 'kinetic-type', 'proof',
        ['board', 'retro'],
        'Grid of monospaced cells flipping to final letters with staggered y/rotation.',
        ['classic', 'modern']),
    recipe('news-ticker', 'News Ticker', 'Dải tin chạy ngang đáy.', 'ui', 'any',
        ['ticker'],
        'Single-line marquee using xPercent finite tween matching ambientDur; avoid repeat:-1.',
        ['classic', 'modern']),
    recipe('flowchart-vertical', 'Vertical Flow', '3 bước quy trình dọc.', 'explainer', 'insight',
        ['flow', 'steps'],
        '3 nodes + connectors; stagger fade/slide; one focus accent per beat.',
        ['modern', 'minimal', 'stickman']),
    recipe('flowchart-horizontal', 'Horizontal Flow', 'A→B→C ngang.', 'explainer', 'insight',
        ['flow'],
        'Horizontal nodes with arrow paths drawn via stroke-dashoffset.',
        ['modern', 'minimal']),
    recipe('comparison-split', 'A vs B Split', 'So sánh hai cột.', 'explainer', 'problem',
        ['compare'],
        '50/50 split with short labels only; animate bars or icons, not paragraphs.',
        ['modern', 'classic', 'minimal']),
    recipe('ai-chat-reveal', 'AI Chat Reveal', 'Variant chat exchange.', 'social', 'problem',
        ['ai', 'chat'],
        'Prefer __block("chat-exchange"). Keep bubbles short (≤12 words).',
        ['modern']),
    recipe('message-thread', 'Message Thread', 'Stack tin nhắn dài hơn.', 'social', 'insight',
        ['thread'],
        'Use __block("chat-exchange") with 3-4 messages; stagger 0.3s.',
        ['modern', 'stickman']),
    recipe('notification-cascade', 'Notification Cascade', 'Toast xếp chồng.', 'ui', 'hook',
        ['notify'],
        '2-3 toast cards stacking from top-right with spring entrance; max 1 line each.',
        ['modern']),
    recipe('macos-notification', 'macOS Notification', 'Banner thông báo mac.', 'ui', 'hook',
        ['os', 'notify'],
        'Rounded banner with app icon circle + title/body microcopy; slide from top.',
        ['modern', 'minimal']),
    recipe('progress-stat', 'Progress Stat', 'Vòng progress + %.', 'dataviz', 'proof',
        ['progress', 'ring'],
        'SVG circle stroke-dashoffset count to target; big % in center.',
        ['modern', 'minimal']),
    recipe('line-graph', 'Line Graph Draw', 'Đường biểu đồ vẽ dần.', 'dataviz', 'proof',
        ['line', 'chart'],
        'SVG polyline/path draw with stroke-dashoffset; markers pop at key points.',
        ['modern', 'classic']),
    recipe('metric-ribbon', 'Metric Ribbon', 'Dải 3 KPI ngang.', 'dataviz', 'proof',
        ['kpi'],
        'Three big numbers with micro labels; count-up stagger; hairline dividers not cards.',
        ['modern', 'minimal']),
    recipe('product-turntable', 'Product Turntable', 'XOAY mockup sản phẩm.', 'device', 'insight',
        ['product', '3d'],
        'Prefer __block("device-showcase") then gentle rotateY ambient.',
        ['modern']),
    recipe('app-showcase', 'App Showcase', 'UI app trong laptop.', 'device', 'insight',
        ['app', 'laptop'],
        '__block("device-showcase", { device:"laptop", screenHtml: compact UI chips }).',
        ['modern', 'minimal']),
    recipe('phone-ui-stack', 'Phone UI Stack', 'Nhiều card UI chồng trong phone.', 'device', 'insight',
        ['phone', 'cards'],
        'Device phone + 2-3 stacked panels sliding up inside screen.',
        ['modern']),
    recipe('code-highlight', 'Code Highlight Sweep', 'Highlight dòng quan trọng.', 'code', 'insight',
        ['code'],
        '__block("code-diff") then animate a highlight rect behind a key line.',
        ['modern', 'minimal']),
    recipe('code-scroll', 'Code Scroll Pane', 'Cuộn đoạn code dài.', 'code', 'insight',
        ['code'],
        'Tall code block with y tween of inner lines; keep IDE chrome stable.',
        ['modern']),
    recipe('glass-hero', 'Glass Hero Panel', 'Hero kính mờ tiết chế.', 'ui', 'hook',
        ['glass', 'hero'],
        'ONE glass panel max as focal plane; pair with kinetic-type; avoid card grids.',
        ['modern']),
    recipe('editorial-quote', 'Editorial Quote', 'Trích dẫn serif lớn.', 'cinematic', 'insight',
        ['quote'],
        'Large italic/serif quote ≤12 words + thin attribution; slow fade/glide.',
        ['classic']),
    recipe('ken-burns-frame', 'Ken Burns Frame', 'Pan/scale khung ảnh SVG.', 'cinematic', 'any',
        ['kenburns'],
        'Slow scale 1→1.08 on a framed visual; zero bounce; classic/cinematic.',
        ['classic']),
    recipe('whip-pan-transition', 'Whip Pan Hint', 'Gợi ý chuyển cảnh whip.', 'transition', 'any',
        ['transition'],
        'End scene with fast x skew + blur-ish opacity; next scene enters opposite side. Finite only.',
        ['modern', 'classic']),
    recipe('zoom-punch', 'Zoom Punch', 'Zoom mạnh vào số/keyword.', 'transition', 'hook',
        ['zoom'],
        'Scale focal anchor 0.7→1.05→1 with short overshoot; good for hook numbers.',
        ['modern', 'stickman']),
    recipe('flash-through-white', 'Flash Cut', 'Flash trắng giữa beat.', 'transition', 'any',
        ['flash'],
        'Full-viewport white overlay opacity 0→1→0 in ≤0.2s at cut point.',
        ['modern', 'classic']),
    recipe('particle-orbit', 'Particle Orbit', 'Điểm sáng quỹ đạo quanh hero.', 'cinematic', 'any',
        ['particles'],
        '6-12 small dots on circular motionPath finite cycles bounded by ambientDur.',
        ['modern']),
    recipe('starfield-drift', 'Starfield Drift', 'Nền sao trôi chậm.', 'cinematic', 'any',
        ['bg'],
        'Sparse dots translating slowly; keep contrast for foreground text.',
        ['modern', 'classic']),
    recipe('comic-impact', 'Comic Impact', 'FX comic + stickman.', 'explainer', 'hook',
        ['stickman', 'fx'],
        'Use window.__sm() + window.__fx("impact"|"shock") with kinetic short title.',
        ['stickman']),
    recipe('speech-bubble-punch', 'Speech Bubble Punch', 'Bong bóng thoại ngắn.', 'explainer', 'insight',
        ['bubble', 'stickman'],
        '≤4 word bubble near stickman; scale pop with back.out.',
        ['stickman']),
    recipe('timeline-era', 'Era Timeline', 'Mốc thời gian ngang.', 'explainer', 'proof',
        ['timeline'],
        'Horizontal ticks + year labels; playhead advances; classic editorial feel.',
        ['classic', 'minimal']),
    recipe('map-pin-focus', 'Map Pin Focus', 'Bản đồ tối giản + pin.', 'explainer', 'proof',
        ['map'],
        'Simplified SVG region + pulsing pin; no real map tiles.',
        ['classic', 'modern']),
    recipe('checklist-reveal', 'Checklist Reveal', 'Danh sách tick lần lượt.', 'explainer', 'insight',
        ['list'],
        '3 items max; checkmark draws in; stickman/modern friendly.',
        ['modern', 'stickman', 'minimal']),
    recipe('price-tag-pop', 'Price Tag Pop', 'Giá / offer pop.', 'ui', 'cta',
        ['price', 'cta'],
        'Large price + micro CTA chip; spring pop then settle.',
        ['modern', 'stickman']),
    recipe('cta-banner', 'CTA Banner', 'Banner kêu gọi hành động.', 'ui', 'cta',
        ['cta'],
        'Short CTA ≤5 words + accent underline draw; pair with logo-outro.',
        ['modern', 'classic', 'minimal']),
    recipe('brand-lockup', 'Brand Lockup', 'Logo + wordmark căn giữa.', 'cinematic', 'cta',
        ['brand'],
        'Mark + wordmark; opacity/y; hold for CTA beat.',
        ['any']),
    recipe('before-after-slider', 'Before/After', 'Che phủ trước/sau.', 'explainer', 'proof',
        ['compare'],
        'Clip-path wipe revealing after state; label chips Before/After.',
        ['modern', 'minimal']),
    recipe('stack-cards-fan', 'Stack Cards Fan', 'Chồng card xòe.', 'ui', 'insight',
        ['cards'],
        'Max 3 cards; fan rotate; only if interaction metaphor needed — else avoid cards.',
        ['modern']),
    recipe('icon-orbit-row', 'Icon Orbit Row', 'Hàng icon bay vào.', 'explainer', 'insight',
        ['icons'],
        '3 inline SVG icons + 1-2 word labels; stagger from below.',
        ['modern', 'minimal', 'stickman']),
    recipe('typewriter-terminal', 'Typewriter Terminal', 'Gõ mono trên nền tối.', 'code', 'hook',
        ['type', 'code'],
        '__block("kinetic-type", { mode:"typewriter", text }) inside a terminal chrome frame.',
        ['modern', 'minimal']),
    recipe('counter-hero', 'Counter Hero', 'Hero số khổng lồ.', 'dataviz', 'hook',
        ['number', 'hook'],
        'One giant number count-up + micro label; optional __block kinetic kicker.',
        ['modern', 'classic', 'minimal']),
    recipe('problem-x-mark', 'Problem X Mark', 'Đánh dấu vấn đề bằng X đỏ.', 'explainer', 'problem',
        ['problem'],
        'Icon/list item crossed by animated X stroke; high contrast accent.',
        ['modern', 'stickman']),
    recipe('solution-check', 'Solution Check', 'Check xanh giải pháp.', 'explainer', 'insight',
        ['solution'],
        'Draw check path; pair with short keyword chip.',
        ['modern', 'stickman', 'minimal']),
    recipe('data-callout', 'Data Callout', 'Callout số nổi trên biểu đồ.', 'dataviz', 'proof',
        ['callout'],
        'Leader line to a bar/point with badge number; use with bar-chart.',
        ['modern', 'classic']),
    recipe('soft-light-leak', 'Soft Light Leak', 'Vệt sáng cinematic.', 'cinematic', 'any',
        ['vfx'],
        'Gradient orb drifting slowly at low opacity; never obscure text.',
        ['classic', 'modern']),
    recipe('rack-focus-hint', 'Rack Focus Hint', 'Đổi nét giữa 2 lớp.', 'cinematic', 'insight',
        ['focus'],
        'Blur filter tween foreground↔background layers (finite); keep text sharp at end.',
        ['classic']),
    recipe('social-proof-row', 'Social Proof Row', 'Logo/khách hàng tối giản.', 'ui', 'proof',
        ['logos'],
        '4-5 monochrome wordmarks fade in; minimal style preferred.',
        ['minimal', 'modern']),
    recipe('chapter-index', 'Chapter Index', 'Số chương kiểu Swiss.', 'kinetic-type', 'hook',
        ['index', 'swiss'],
        '"01 / TITLE" monolithic layout; precision power3.out; minimal palette.',
        ['minimal']),
];

export const motionBlocks: MotionBlock[] = [...coreBlocks, ...recipeBlocks];

export const cinematicBlueprints: CinematicBlueprint[] = [
    {
        id: 'faceless-explainer',
        name: 'Faceless Explainer',
        description: '5 nhịp giải thích không mặt người: hook chữ → nỗi đau → insight → data → CTA.',
        styleAffinity: ['modern', 'minimal'],
        suggestedBlocks: ['kinetic-type', 'chat-exchange', 'code-diff', 'bar-chart', 'logo-outro'],
        beatPlan: [
            'Hook: kinetic-type punch question/number',
            'Problem: chat-exchange or problem-x-mark',
            'Insight: code-diff or flowchart',
            'Proof: bar-chart / metric-ribbon',
            'CTA: cta-banner + logo-outro',
        ],
        promptSnippet:
            'Follow faceless-explainer blueprint. Map scenes to Hook→Problem→Insight→Proof→CTA. Prefer runtime __block helpers listed in suggestedBlocks.',
    },
    {
        id: 'saas-launch',
        name: 'SaaS Launch',
        description: 'Ra mắt sản phẩm SaaS với device mockup và metric proof.',
        styleAffinity: ['modern'],
        suggestedBlocks: ['kinetic-type', 'device-showcase', 'bar-chart', 'notification-cascade', 'cta-banner'],
        beatPlan: [
            'Hook: kinetic-type product promise',
            'Problem: notification-cascade pain',
            'Insight: device-showcase product UI',
            'Proof: bar-chart metrics',
            'CTA: cta-banner',
        ],
        promptSnippet: 'SaaS launch spine. Showcase UI in device-showcase; prove with bar-chart; end with crisp CTA.',
    },
    {
        id: 'developer-story',
        name: 'Developer Story',
        description: 'Câu chuyện cho developer: terminal, diff, ship.',
        styleAffinity: ['modern', 'minimal'],
        suggestedBlocks: ['terminal-typing', 'code-diff', 'checklist-reveal', 'bar-chart', 'logo-outro'],
        beatPlan: [
            'Hook: terminal-typing provocative command',
            'Problem: broken code / del lines',
            'Insight: code-diff add lines',
            'Proof: checklist or metrics',
            'CTA: logo-outro ship it',
        ],
        promptSnippet: 'Developer narrative. Lean on code-diff heavily; keep on-screen text monospace-friendly labels only.',
    },
    {
        id: 'documentary-editorial',
        name: 'Documentary Editorial',
        description: 'Phong cách tạp chí / tài liệu với quote và timeline.',
        styleAffinity: ['classic'],
        suggestedBlocks: ['editorial-quote', 'ken-burns-frame', 'timeline-era', 'lower-third-editorial', 'logo-outro'],
        beatPlan: [
            'Hook: editorial-quote or ken-burns',
            'Problem: era tension via timeline',
            'Insight: quote / map-pin',
            'Proof: timeline-era data beat',
            'CTA: lower-third + logo',
        ],
        promptSnippet: 'Editorial documentary spine. Slow easings, serif, no neon, no bounce.',
    },
    {
        id: 'comic-explainer',
        name: 'Comic Stickman Explainer',
        description: 'Giải thích dí dỏm với stickman + bubble.',
        styleAffinity: ['stickman'],
        suggestedBlocks: ['comic-impact', 'speech-bubble-punch', 'chat-exchange', 'checklist-reveal', 'price-tag-pop'],
        beatPlan: [
            'Hook: comic-impact + short title',
            'Problem: stickman stress + bubble',
            'Insight: checklist or chat',
            'Proof: simple comparison',
            'CTA: price-tag-pop / punchline',
        ],
        promptSnippet: 'Use __sm/__fx with comic beats. Keep text handwritten style; punchy ≤4 word bubbles.',
    },
    {
        id: 'swiss-minimal-brief',
        name: 'Swiss Minimal Brief',
        description: 'Tối giản Thụy Sĩ: index, whitespace, một accent.',
        styleAffinity: ['minimal'],
        suggestedBlocks: ['chapter-index', 'mask-reveal-title', 'metric-ribbon', 'social-proof-row', 'brand-lockup'],
        beatPlan: [
            'Hook: chapter-index',
            'Problem: single stark statement',
            'Insight: mask-reveal keyword',
            'Proof: metric-ribbon',
            'CTA: brand-lockup',
        ],
        promptSnippet: 'Swiss restraint. Max 2 moving elements per beat. Hairlines over cards. One accent color.',
    },
    {
        id: 'ai-product-demo',
        name: 'AI Product Demo',
        description: 'Demo trợ lý AI: chat → insight → device.',
        styleAffinity: ['modern'],
        suggestedBlocks: ['chat-exchange', 'kinetic-type', 'device-showcase', 'bar-chart', 'cta-banner'],
        beatPlan: [
            'Hook: kinetic question',
            'Problem: chat-exchange user pain',
            'Insight: assistant answer + device UI',
            'Proof: bar-chart uplift',
            'CTA: cta-banner',
        ],
        promptSnippet: 'AI demo blueprint. Chat bubbles short; show product in device-showcase; quantify with bar-chart.',
    },
    {
        id: 'data-story',
        name: 'Data Story',
        description: 'Kể chuyện bằng số liệu và biểu đồ.',
        styleAffinity: ['modern', 'classic', 'minimal'],
        suggestedBlocks: ['counter-hero', 'bar-chart', 'line-graph', 'data-callout', 'cta-banner'],
        beatPlan: [
            'Hook: counter-hero shocking number',
            'Problem: context gap',
            'Insight: line-graph trend',
            'Proof: bar-chart + callout',
            'CTA: implication CTA',
        ],
        promptSnippet: 'Lead with numbers. Every scene needs one clear metric anchor. Prefer __block("bar-chart").',
    },
];

export function listMotionBlocks(): MotionBlock[] {
    return motionBlocks;
}

export function listBlueprints(): CinematicBlueprint[] {
    return cinematicBlueprints;
}

export function getMotionBlock(id: string): MotionBlock | undefined {
    return motionBlocks.find((b) => b.id === id);
}

export function getBlueprint(id: string): CinematicBlueprint | undefined {
    return cinematicBlueprints.find((b) => b.id === id);
}

export function getBlocksForStyle(style: string): MotionBlock[] {
    return motionBlocks.filter(
        (b) => b.styleAffinity.includes('any') || b.styleAffinity.includes(style as StyleAffinity)
    );
}
